# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constrain/bt_uart_EGo.xdc

# XDC: imports/constrain/top_sim.xdc

# IP: ip/char_fifo/char_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==char_fifo || ORIG_REF_NAME==char_fifo} -quiet] -quiet

# IP: ip/clk_core/clk_core.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_core || ORIG_REF_NAME==clk_core} -quiet] -quiet
