# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/Counter.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/audio.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/bluetooth.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/bonetime.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/clean_mode_counter.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/clk_div.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/clk_gen.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/clock.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/cmd_parse.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/data_select.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/debounce.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/debouncer.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/gesture_control.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/lb_ctl.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/meta_harden.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/mode.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/on_off.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/reminder.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/reset_bridge.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/resp_gen.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/rst_gen.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/set_gesture_time.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/set_reminder.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/show_number.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/three_Counter.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/three_return_Counter.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/to_bcd.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/uart_baud_gen.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/uart_rx.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/uart_rx_ctl.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/uart_tx.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/uart_tx_ctl.v}
  {C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/imports/new/Top.v}
}
read_ip -quiet {{C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/ip/char_fifo/char_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/ip/char_fifo/char_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/ip/char_fifo/char_fifo_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/ip/char_fifo/char_fifo_ooc.xdc}}]

read_ip -quiet {{C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/ip/clk_core/clk_core.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/ip/clk_core/clk_core_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/ip/clk_core/clk_core.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/sources_1/ip/clk_core/clk_core_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/constrs_1/imports/constrain/bt_uart_EGo.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/constrs_1/imports/constrain/bt_uart_EGo.xdc}}]

read_xdc {{C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/constrs_1/imports/constrain/top_sim.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Alessandro Paschen/Downloads/project_final_no_update_counter_when_close/project_final/project_final.srcs/constrs_1/imports/constrain/top_sim.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
